# Generated by Django 2.2.5 on 2019-11-15 05:55

import datetime
import defdb.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cid', models.IntegerField()),
                ('cname', models.CharField(max_length=20)),
                ('cphno', models.IntegerField(verbose_name=10)),
                ('cemail', models.CharField(max_length=20, validators=[django.core.validators.EmailValidator])),
                ('caddress', models.CharField(max_length=50)),
                ('cstate', models.CharField(choices=[('T', 'Telangana'), ('A', 'AndhraPradesh')], max_length=1)),
                ('ccountry', models.CharField(default=defdb.models.default_country, help_text='Ensure to provide your country', max_length=30)),
                ('date', models.DateField(default=datetime.date.today)),
            ],
        ),
    ]
