# Generated by Django 2.2.5 on 2019-11-15 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('defdb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='cphno',
            field=models.CharField(max_length=10),
        ),
    ]
